id: P003135
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:42.924566
source_metadata:
  id: bdr:W30519
  title: བསྐུ་མཉེའི་ལག་དེབ།
  author: ''
  volumes:
    41ad8eb2886e445abe9b5659232f51e4:
      image_group_id: I1KG21795
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
